#! /usr/bin/env bash

################################################################################

cmake_source_dir="@CMAKE_SOURCE_DIR@"
cmake_binary_dir="@CMAKE_BINARY_DIR@"

panic()
{
	echo "ERROR: $*"
	exit 1
}

run_command()
{
	echo "RUNNING: $*"
	"$@"
	local status=$?
	echo "EXIT STATUS: $status"
	return "$status"
}

run_command_discard_stdout()
{
	echo "RUNNING: $*"
	"$@" >& /dev/null
	local status=$?
	echo "EXIT STATUS: $status"
	return "$status"
}

maybe_run_command()
{
	[ -x "$1" ] || return 0
	run_command "$@"
}

source_dir="$cmake_source_dir"
build_dir="$cmake_binary_dir"

################################################################################

ls_program="$(type -P ls)" || panic "cannot find ls program"
true_program="$(type -P true)" || panic "cannot find true program"

echo "============================================================"
cat "$build_dir/syscall_names.hpp"
echo "============================================================"

run_command \
  "$build_dir/ptrace_1" "$ls_program" / || \
  panic "program failed"
run_command \
  "$build_dir/ptrace_2" || \
  panic "program failed"
run_command_discard_stdout \
  "$build_dir/ptrace_3" "$true_program" || \
  panic "program failed"
