#! /usr/bin/env bash

################################################################################

cmake_source_dir="@CMAKE_SOURCE_DIR@"
cmake_binary_dir="@CMAKE_BINARY_DIR@"

panic()
{
	echo "ERROR: $*"
	exit 1
}

run_command()
{
	echo "RUNNING: $*"
	"$@"
	local status=$?
	echo "EXIT STATUS: $status"
	return "$status"
}

source_dir="$cmake_source_dir"
build_dir="$cmake_binary_dir"

################################################################################

for ((i = 0; i < 4; ++i)); do
	run_command \
	  "$build_dir/aslr_nopie" || \
	  panic "program failed"
done

for ((i = 0; i < 4; ++i)); do
	run_command \
	  "$build_dir/aslr_pie" || \
	  panic "program failed"
done
